### PR TITLE
Api Service Snippet 

### PR DESCRIPTION
**Pull request by chrisksamueljr**
For this snippet we can show how to code your Api Service for handling communicating with a public api

### CODE REVIEW

**Comment by NothingEverHappens** [comment]
Please shorten it up and update

**Comment by fetis** [comment]
I didn't get the point of this snippet. What problem does it solve?

**Comment by NothingEverHappens** [comment]
@chrisksamueljr PTAL

**Comment by kirjs** [comment]
Closing as I haven't heard from you for a while lol

**Pull request closed without merging**
