### PR TITLE
Add - new snippet: Hammer.js

### PR DESCRIPTION
**Pull request by MichaelSolati**

### CODE REVIEW

**Review by thekiba — APPROVED** [review]

**Comment by MichaelSolati** [comment]
I just realized I could give a sample of applying hammerjs to an element in a component and not just as a hostlistener. Please allow me a sec to apply that.

**Comment by thekiba** [comment]
@MichaelSolati great work! Can you put another snippet in the Bonus block with extra description?
You can check example here https://github.com/nycJSorg/30-seconds-of-angular/blob/master/snippets/adding-keyboard-shortcuts-to-elements.md

**Comment by MichaelSolati** [comment]
@thekiba should I just do this for the event bindings or also the host listeners?

**Comment by thekiba** [comment]
@MichaelSolati only for event bindings. "Also you can applying hammerjs events to elements in the template" something like that :)

**Comment by kirjs** [comment]
Pls add bonus section and let's merge this in

**Review by kirjs — APPROVED** [review]

**Review by kirjs — APPROVED** [review]

**Pull request merged**
